name: Update documentation

on:
  push:
    branches:
      - main
    paths:
      - 'v2/api-reference.md'

permissions:
  contents: write
  id-token: write

jobs:
  update-docs:
    name: Update documentation in target repository
    uses: kartverket/github-workflows/.github/workflows/update-skip-docs.yaml@6ab0680e9e0ffb14631c3108c11c00b60bd9e242
    with:
      source_path: "v2/api-reference.md"
      target_path: "docs/03-applikasjon-utrulling/10-argokit/09-argokit-v2.md"
      branch_name: "update-argokitv2-docs-branch"
      author_name: "GithubActions <argokit@kartverket.no>"
      identity: "argokit"